error:
… from call site

  at ./default.nix:51:25:

    50|
    51|   oci-image-generator = callPackage ./pkgs/oci-image-generator-nixos/default.nix { };
      |                         ^
    52|

… while calling 'callPackageWith'

  at <nixpkgs> + /lib/customisation.nix:240:19:

   239|   callPackageWith =
   240|     autoArgs: fn: args:
      |                   ^
   241|     let

error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "writeReferencesToFile" at ./pkgs/oci-image-generator-nixos/default.nix:34'
